language: csharp
os:
  - linux
  - osx
dist: trusty
mono:
  - latest
dotnet: 2.0.0
script:
  - ./build.sh --target "Travis" --platform "Any CPU" --configuration "Release"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/50f0e32a0792fbdc22f1
    on_success: change
    on_failure: always
    on_start: never