image: Visual Studio 2015
platform:
- Any CPU
configuration:
- Release
environment:
    NUGET_API_KEY:
        secure: hhbS2wZt4ThH2rkbor0IPG1uwCaP6oX6KHbSlrXkyqNHtjVwm+pQlIVvb6rQ79/R
    NUGET_API_URL: https://www.nuget.org/api/v2/package
    MYGET_API_KEY:
        secure: 87qeRHxguio5xFkV5rdt3oQ2pnSQ5NZZf0DFbD/PbFk4/pMexvd9puCcip/4Rp0J
    MYGET_API_URL: https://www.myget.org/F/mabiavalon-ci/api/v2/package
build_script:
- ps: .\build.ps1 -Target "AppVeyor" -Platform "$env:platform" -Configuration "$env:configuration"
test: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/821f977b3fba1510f4a6
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
artifacts:
  - path: artifacts\test-results\*.xml
  - path: artifacts\nuget\*.nupkg
  - path: artifacts\zip\*.zip

